version: "3.9"

services:
  repository-management:
    container_name: repository-management
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - NODE_ENV=production
    networks:
      - ntt-network

networks:
  ntt-network:
    name: ntt-network

